name: Flask Task Runner

on:
  push:
    branches:
      - master
      
  

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Run Flask Task
        env:
          FLASK_ENV: development
        run: |
          # Replace the following command with the task you want to run
          python hello.py
